name: "Test Bump-up the version manually"

on:
  workflow_dispatch:
    inputs:
      flag:
        required: true
        type: string
        description: "Flag like dev, patch and release."
      currentVersion:
        required: true
        type: string
        description: "Current version in the VERSION files."

jobs:
  testbumpupversion:
    uses: ./.github/workflows/bump-version.yml
    with:
      flag: ${{ inputs.flag }}
      currentVersion: ${{ inputs.currentVersion }}